class ApiEndPoint {
  static String baseUrl = "https://tradeapi.cygnux.in/api/v1/";
  // static String baseUrl = "https://traderpuatapi.cygnux.in/api/v1/";
  // static String baseUrl = "http://192.168.0.180:4032/api/v1/";

  static String logIn = "${baseUrl}auth/login";
  static String leadSource = "${baseUrl}commonMaster/findByGroup?type=Lead+Source";
  static String leadTags = "${baseUrl}commonMaster/findByGroup?type=Tag+Type";
  static String priceType = "${baseUrl}commonMaster/findByGroup?type=Price+Type";
  static String addressType = "${baseUrl}commonMaster/findByGroup?type=Address+Type";
  static String state = "${baseUrl}state/dropdown";
  static String city = "${baseUrl}city/dropdown";
  static String pinCode = "${baseUrl}pin/dropdown";
  static String country = "${baseUrl}country/dropdown";
  static String leadSubmit = "${baseUrl}customer/create";
  static String leadList = "${baseUrl}customer/find";
  static String deleteLead = "${baseUrl}customer/delete/";
  static String editLead = "${baseUrl}customer/update/";
  static String pickingList = "${baseUrl}picking-list/find";
  static String pickingCounts = "${baseUrl}picking-list/counts";
  static String pickingDetail = "${baseUrl}picking-list/find/";
  static String pickingSuggestions = "${baseUrl}picking-list/suggestions";
  static String pickingUpdate = "${baseUrl}picking-list/update-item/";
  static String pickingSubmitPick = "${baseUrl}picking-list/submit-pick";
  static String pickingReject = "${baseUrl}picking-list/reject/";
  static String inquiryView = "${baseUrl}customer/find/";
  static String oppTags = "${baseUrl}commonMaster/findByGroup?type=Tag+Type";
  static String oppLabel = "${baseUrl}commonMaster/findByGroup?type=Lead+Label";
  static String oppSource = "${baseUrl}commonMaster/findByGroup?type=Lead+Source";
  static String oppActivityStatus = "${baseUrl}commonMaster/findByGroup?type=Lead+Activity+Status";
  static String oppActivityType = "${baseUrl}commonMaster/findByGroup?type=Lead+Activity+Type";
  static String oppContactName = "${baseUrl}customer/find";
  static String opportunityProduct = "${baseUrl}product/find";
  static String productCategory = "${baseUrl}commonMaster/findByGroup?type=Product+Category";
  static String assignSalesPerson = "${baseUrl}users/userDropDown";
  static String opportunitySave = "${baseUrl}opportunity/create";
  static String opportunityList = "${baseUrl}opportunity/find";
  static String opportunityOverview = "${baseUrl}opportunity/overview/";
  static String addLog = "${baseUrl}entity-log/create";
  static String leadDetail = "${baseUrl}opportunity/find/";
  static String leadUpdate = "${baseUrl}opportunity/update/";
  static String activityCreate = "${baseUrl}activity/create";
  static String activityDetail = "${baseUrl}activity/find/";
  static String opportunityDelete = "${baseUrl}opportunity/delete/";
  static String opportunityAssign = "${baseUrl}opportunity/assign/";
  static String opportunitySummary = "${baseUrl}opportunity/summary";
  static String opportunitySearchSuggestions = "${baseUrl}opportunity/search-suggestions";
  static String getCustomerGroup = "${baseUrl}group-brand-master/find";
  static String getLocation = "${baseUrl}location/find";
  static String getCompany = "${baseUrl}company-master/find?exportData=false";
  static String getFollowerAndViewer = "${baseUrl}company-master/find?exportData=false";
  static String getProbability = "${baseUrl}commonMaster/findByGroup?type=Probability";
  static String getOpportunitySection = "${baseUrl}section/find?page=1&limit=50&exportData=false";
  static String getOpportunitySectionUpdate = "${baseUrl}opportunity/section-update/";
  static String customerContactPersonList = "${baseUrl}customer-contact-person/list";
  static String customerContactPersonCreate = "${baseUrl}customer-contact-person/create";

  // Packing Endpoints
  static String packingList = "${baseUrl}packing-list/find";
  static String packingCounts = "${baseUrl}packing-list/counts";
  static String packingDetail = "${baseUrl}packing-list/find/";
  static String createFromPicking = "${baseUrl}packing-list/create-from-picking";
  static String startPacking = "${baseUrl}packing-list/start-packing";
  static String updatePackedQty = "${baseUrl}packing-list/update-item";
  static String completePacking = "${baseUrl}packing-list/complete-packing";
  static String requestInvoice = "${baseUrl}packing-list/send-to-invoice";
  static String requestEWayBill = "${baseUrl}packing-list/request-e-way-bill";
  static String viewPackingList = "${baseUrl}packing-list/view-pdf/";
  static String packingListBoxWise = "${baseUrl}packing-list/view-box-wise-pdf/";
  static String shippingLabel = "${baseUrl}packing-list/shipping-label";
  static String shippingLabelPdf = "${baseUrl}packing-list/shipping-label-pdf/";
  static String packingPhysicalBoxStatus = "${baseUrl}packing-list/physical-box/status";
  static String packingReject = "${baseUrl}packing-list/reject/";
  static String transporters = "${baseUrl}vendor/transporters";
  static String transportMode = "${baseUrl}commonMaster/findByGroup?type=Transport+Mode";
  static String boxSuggestion = "${baseUrl}packing-list/box-suggestion";
  static String updateBoxConfig = "${baseUrl}packing-list/physical-box/update/";
  static String updateBoxSuggestion = "${baseUrl}packing-list/box-suggestion/update/by-packing";

  // Visit Endpoints
  static String serviceVisitCounts = "${baseUrl}service-visit/counts";
  static String serviceVisitList = "${baseUrl}service-visit/find";
}
